
<?php

require('PHPMailer/PHPMailerAutoload.php');
require_once('connection.php');

$company_name = $_POST['company_name'];
$full_name = $_POST['full_name'];
$email = $_POST['email'];
$phone = $_POST['phone'];
$location = $_POST['location'];
$description = $_POST['description'];
$shipping_address = $_POST['shipping_address'];
$product = $_POST['product'];


$query = "INSERT INTO ticket VALUES ('','$company_name','$location','$full_name','$email','$phone','$shipping_address','','$product','$description','Open','')";
$res=mysql_query($query,$dbh);

$query = "SELECT idticket FROM ticket ORDER BY idticket DESC limit 1";
$res=mysql_query($query,$dbh);
$row = mysql_fetch_array($res,1);
$num = $row['idticket'];

$auto = "This is an automatic message generated by ED Imaging Solutions Ticketing System\n\n";
$body = $auto."\nTicket #: ".$num."\n"."Company Name: ".$company_name."\n"."Full Name: ".$full_name."\n"."Email: ".$email."\n"."Phone number: ".$phone."\n"."Location: ".$location."\n"."Shipping Address: ".$shipping_address."\n"."Description: ".$description."\n\n\n"."--------------------------------------------------------------------------\n"."Powered By: Agloz Software - Copyright 2016"."\n"."www.aglozsoftware.com\n";


$mail = new PHPMailer;
//$mail->isSMTP();
$mail->Host = 'smtp.mandrillapp.com';
$mail->SMTPAuth = true;
$mail->Username = 'maguilarce@gmail.com';
$mail->Password = 'grF3xKSBRAA7ka9OxqK34A';
$mail->SMTPSecure = 'tls';
$mail->Port = 25;
$mail->From = $email;
$mail->FromName = $full_name;
$mail->addAddress('robert@edimaging.solutions');
//$mail->addAddress('robert@edimaging.solutions');
$mail->addCC('info@edimaging.solutions');
//$mail->addAddress('rhewitt01@yahoo.com');
//$mail->addCC('maguilar@aglozsoftware.com');


$mail->Subject = "LJA ENGINEERING INC - Ticket #".$num;
$mail->Body = $body;
$mail->Send();

if(!$mail->Send()) {
 // echo "Mailer Error: " . $mail->ErrorInfo;
} else {
  //echo "Message sent!";
}


?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Contact Us</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <meta name="description" content="Developed By M Abdur Rokib Promy">
        <meta name="keywords" content="Admin, Bootstrap 3, Template, Theme, Responsive">
        <link rel="icon" href="img/favicon.ico" type="image/x-icon"/>
        <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon"/>
        <!-- bootstrap 3.0.2 -->
        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
        <link href="css/ionicons.min.css" rel="stylesheet" type="text/css" />

        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <!-- Theme style -->
        <link href="css/style.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="skin-black">
       
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside >
                <!-- sidebar: style can be found in sidebar.less -->
                <img draggable="false" height="100" width="160" src="img/edi.jpg" />
               
            </aside>

            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <!-- Content Header (Page header) -->


                <!-- Main content -->
               
                    <div class="row">
                      
                        
                    
                    <form method="post>"
                        <div class="row">
                            <div class="col-md-10">
                                <section class="panel">
                                    <header class="panel-heading">
                                        Contact Us
                                    </header>
                                    <div class="panel-body">
                                        <p>Your email has been sent. You will get a reply soon.</p>
                                                                            <div class="form-group">
                                          <div class="col-lg-offset-2 col-lg-10">
                                              <button formaction="contactus.php" type="submit" class="btn btn-danger">Back</button>
                                          </div>
                                      </div>
                                    </div>

                                </section>
                            </div>
                        </div>
                    </form>

                <!-- /.content -->
            </aside><!-- /.right-side -->
            <div class="footer-main">
                <p>Powered by</p>
                <img draggable="false" height="60" width="40" src="img/agloz.jpg" />
                <p><a href="http://www.aglozsoftware.com">www.aglozsoftware.com</a></p>
                <p>&copy 2016</p>
                
            </div>
        </div><!-- ./wrapper -->
        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <script src="js/jquery.min.js" type="text/javascript"></script>

        <!-- Bootstrap -->
        <script src="js/bootstrap.min.js" type="text/javascript"></script>
        <!-- Director App -->
        <script src="js/Director/app.js" type="text/javascript"></script>
    </body>
</html>